# -*- coding: utf-8 -*-
"""senahalka_library.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UMR6HlJtq6fwjzkjr3TCYAC8rypndphT
"""



from tabulate import tabulate

class Library:
    def __init__(self):
        self.file = open("books.txt", "a+")

    def __del__(self):
        self.file.close()

    def list_books(self):
        self.file.seek(0)
        book_lines = self.file.read().splitlines()
        books_data = [line.split(",") for line in book_lines]
        print(tabulate(books_data, headers=["Title", "Author", "Release Year", "Pages"], tablefmt="fancy_grid"))

    def add_book(self, title, author, release_year, pages):
        book_info = f"{title}, {author}, {release_year}, {pages}\n"
        self.file.write(book_info)
        print("Book added successfully!")

    def remove_book(self):
        title_to_remove = input("Enter the title of the book to remove: ")
        self.file.seek(0)
        books = self.file.read().splitlines()
        updated_books = [book for book in books if title_to_remove not in book]
        self.file.seek(0)
        self.file.truncate()
        self.file.writelines('\n'.join(updated_books))
        print("Book removed successfully!")


lib = Library()

while True:
    print("\n*** MENU ***")
    print("1) List Books")
    print("2) Add Book")
    print("3) Remove Book")
    print("4) Quit")
    choice = input("Enter your choice: ")

    if choice == "1":
        lib.list_books()
    elif choice == "2":
        title = input("Enter book title: ")
        author = input("Enter book author: ")
        release_year = input("Enter first release year: ")
        pages = input("Enter number of pages: ")
        lib.add_book(title, author, release_year, pages)
    elif choice == "3":
        lib.remove_book()
    elif choice == "4":
        break
    else:
        print("Invalid choice")